language: objective-c

osx_image: xcode7

before_install:
  - git submodule update --init --recursive
  - gem install cocoapods

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - rake build:ios DESTINATION='OS=8.4,name=iPhone 6'
  - rake build:ios DESTINATION='platform=iOS Simulator,name=iPhone 6s Plus'
  - pod lib lint --quick
